export * from './movieInterface'
export * from './charactersInterface'
export * from './oneMovieInteface'
export * from './genresInterface'
export * from './keyWordInterface'
export * from './trailerInterface'
